sudo: required
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - node_modules
    - '$HOME/.cache/'
language:
  - node_js
  - python
python:
  - '3.6'
node_js:
  - 10.10.0
stages:
  - name: update_depends
    if: type IN (cron)
  - name: build
    if: type IN (push, pull_request)
  - name: deploy
    if: branch IN (prod, newreact) and type = push
jobs:
  include:
    - stage: build
      script:
        - . ./scripts/build.sh
    - stage: deploy
      script:
        - . ./scripts/build.sh
        - pip install ansible --user
        - pip install docker --user
        - openssl aes-256-cbc -K $encrypted_71512d77c8b2_key  -iv $encrypted_71512d77c8b2_iv  -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - ./scripts/deployToGCS.sh temperature_hub_poll
        - ./scripts/deployAnsible.sh
    - stage: update_depends
      script:
        - ./scripts/updateDepends.sh
        - yarn run lint
        - yarn run test
        - yarn run coverage
        - yarn global add codeclimate-test-reporter
        - codeclimate-test-reporter < coverage/lcov.info
        - yarn run build
      after_success:
        - openssl aes-256-cbc -K $encrypted_71512d77c8b2_key  -iv $encrypted_71512d77c8b2_key  -in secrets.tar.enc -out secrets.tar -d
        - openssl aes-256-cbc -K $encrypted_a0cd21cf00de_key -iv $encrypted_a0cd21cf00de_iv -in client-secret.json.enc -out client-secret.json -d
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - tar xvf secrets.tar
        - chmod 400 travis
        - eval "$(ssh-agent -s)"
        - ssh-add travis
        - git remote add deploy git@github.com:hartalex/temperature_hub.git
        - npm version patch -f -m "%s - Cron Auto Update Dependencies [ci skip]"
        - git push deploy HEAD:master
notifications:
    slack: hartcode:GqPCaLxnPqXfPJBMjJbEvG81
addons:
  code_climate:
    repo_token: 88e230696fc91873bf0c15bee7de1fcdad7d63b351ffdeae823f68f14ef20f2a
